  services:
  - type: web
    name: bio-nano-reclaimer
    env: python
    plan: free
    buildCommand: cd "prueba 3/BIOIA_LAB/backend" && pip install -r requirements.txt
    startCommand: cd "prueba 3/BIOIA_LAB/backend" && uvicorn main:app --host 0.0.0.0 --port $PORT